### ISSUE TITLE
Update `instabug_flutter` version

### ISSUE THREAD

**Issue by FabianVarela** [Instabug/Instabug-Dio-Interceptor#25]
Hi there ✋ 

I was updating the `instabug_flutter` version to `12.5.0` and using the `instabug_dio_interceptor` package in its latest version (`2.2.0`). However, the error below appears when I try to update the `instabug_flutter`.

![Screenshot 2024-01-09 at 4 46 14 PM](https://github.com/Instabug/Instabug-Dio-Interceptor/assets/8941029/772a3d70-688b-4ee1-bcf8-5a3773b24521)

**Comment by RamithRD** [comment]
cc @abdelhamid-f-nasser @TheBuggedYRN 

Can we get an eta on this 🙏

**Comment by ahmedAlaaInstabug** [comment]
Hi @FabianVarela ,
we will update the dependency until that , you can use **dependancy_override** to overcome this error
```
dependencies:
  flutter:
    sdk: flutter
  # other dependencies...
  instabug_flutter: ^12.5.0

dependency_overrides:
  instabug_flutter: ^12.5.0
```
